@startuml User
title 충북대사범대학부설고등학교 웹포털 사용자 흐름

actor "사용자" as user

rectangle "웹포털" {
    card "메인 페이지" as main
    rectangle "토큰 확인" as token_check
    collections "메뉴 바" as menu
    card "로그인 페이지" as login
    card "회원가입 페이지" as register
    card "계정 설정 페이지" as account_settings
    card "시간표" as time_table {
        card "과목" as subject_abbreviation
    }
}

user --> token_check : 접속

token_check --> main : 토큰 있음
token_check --> login : 토큰 없음

login --> register : 회원가입 버튼 클릭
main <--> menu : 메뉴 이동
menu --> account_settings : 계정 설정 클릭
menu --> time_table : 시간표 보기

@enduml